
#
# riscv32imc-unknown-none-elf

[target.riscv32imc-unknown-none-elf]
# using gcc (gnu tools for linking)
rustflags = [
    "-C",
    "linker=riscv32-unknown-elf-gcc", # <- maybe too old
    "-C",
    "link-arg=-Wl,-Tlink.x",
    "-C",
    "link-arg=-nostartfiles",
]

[target.riscv32emc-unknown-none-elf]
# using gcc (gnu tools for linking)
rustflags = [
    "-C",
    "linker=riscv32-unknown-elf-gcc", # <- maybe too old
    "-C",
    "link-arg=-Wl,-Tlink.x",
    "-C",
    "link-arg=-nostartfiles",
]

# We cannot currently use llvm18 lld, maybe Rust specific patches are required?

# [target.riscv32emc-unknown-none-elf]
# # using gcc (gnu tools for linking)
# rustflags = [
#     "-C",
#     "linker=/data/riscv/llvm-project/build/bin/lld",
#     "-C",
#     "link-arg=-Tlink.x",
# ]


[build]
# target = "riscv32imc-unknown-none-elf"
target = "riscv32emc-unknown-none-elf"
